//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Contiene
    {
        public int IdPedido { get; set; }
        public string CodigoBarra { get; set; }
        public int Cantidad { get; set; }
        public decimal Total { get; set; }
    
        public virtual ArticuloVenta ArticuloVenta { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
