//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Direccion
    {
        public int Id { get; set; }
        public string Calle { get; set; }
        public string Ciudad { get; set; }
        public string CodigoPostal { get; set; }
        public string NumeroInterior { get; set; }
        public string Referencias { get; set; }
        public string NumeroExterior { get; set; }
        public string EntidadFederativa { get; set; }
        public int IdPersona { get; set; }
        public string Colonia { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
