//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int Id { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string Ciudad { get; set; }
        public string CodigoPostal { get; set; }
        public string NumeroInterior { get; set; }
        public string Referencias { get; set; }
        public string NumeroExterior { get; set; }
        public string EntidadFederativa { get; set; }
        public int IdPersona { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
