//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoExtra
    {
        public int Id { get; set; }
        public string Comentario { get; set; }
        public decimal Total { get; set; }
        public int IdTipoGasto { get; set; }
        public string NumeroEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual TipoGasto TipoGasto { get; set; }
    }
}
