//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Guarda
    {
        public int IdEfectivo { get; set; }
        public int IdReporteCaja { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Efectivo Efectivo { get; set; }
        public virtual ReporteCaja ReporteCaja { get; set; }
    }
}
