//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Merma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merma()
        {
            this.Indica = new ObservableCollection<Indica>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Justificacion { get; set; }
        public Nullable<int> IdPedido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Indica> Indica { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
