//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Contiene = new HashSet<Contiene>();
            this.Merma = new HashSet<Merma>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public int IdPersona { get; set; }
        public int IdEstatusPedido { get; set; }
        public string NumeroEmpleado { get; set; }
        public int IdTipoPedido { get; set; }
        public Nullable<int> IdRepartidor { get; set; }
        public Nullable<int> IdMesa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contiene> Contiene { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual EstatusPedido EstatusPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merma> Merma { get; set; }
        public virtual Mesa Mesa { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Repartidor Repartidor { get; set; }
        public virtual TipoPedido TipoPedido { get; set; }
    }
}
