//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporta
    {
        public int IdReporte { get; set; }
        public string CodigoBarra { get; set; }
        public decimal CantidadEnInventario { get; set; }
        public decimal CantidadReal { get; set; }
        public string Comentario { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual ReporteInventario ReporteInventario { get; set; }
    }
}
