//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReporteCaja()
        {
            this.Guarda = new HashSet<Guarda>();
        }
    
        public int Id { get; set; }
        public decimal BalanceDiario { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal TotalEntrada { get; set; }
        public decimal TotalSalida { get; set; }
        public decimal TotalEfectivoContado { get; set; }
        public string Observaciones { get; set; }
        public string NumeroEmpleado { get; set; }
        public decimal EfectivoDiaSiguiente { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guarda> Guarda { get; set; }
    }
}
