//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Solicita
    {
        public int IdPedidoDeProducto { get; set; }
        public string CodigoBarra { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual PedidoAProveedor PedidoAProveedor { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
