//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicita
    {
        public int IdPedidoDeProducto { get; set; }
        public string CodigoBarra { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual PedidoAProveedor PedidoAProveedor { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
